[package]
name = "blip"
version = "0.1.0-alpha.5"
authors = ["nytopop <ericizoita@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A framework for writing in-process gRPC mesh services."
homepage = "https://github.com/nytopop/blip"
repository = "https://github.com/nytopop/blip"
documentation = "https://docs.rs/blip"
keywords = ["rapid", "membership", "mesh", "grpc", "cluster"]
categories = ["network-programming", "asynchronous"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
simulation = [
	"hyper",
	"tower",
	"tower-service",
	"tower-load",
	"tower-make",
	"pin-project"
]

[dependencies]
prost = "0.6"
bytes = "0.5"
http = "0.2"
tracing = "0.1"
fnv = "1.0"
rand = "0.7"
failure = "0.1"
failure_derive = "0.1"

[dependencies.tonic]
version = "0.1"
features = [ "transport" , "tls" ]

[dependencies.futures]
version = "0.3"
features = [ "alloc" ]

[dependencies.tokio]
version = "0.2"
features = [
  "sync",
  "rt-threaded",
  "time",
  "stream",
  "macros"
]

[dependencies.hyper]
version = "0.13"
optional = true

[dependencies.tower]
version = "0.3"
optional = true

[dependencies.tower-service]
version = "0.3"
optional = true

[dependencies.tower-load]
version = "0.3"
optional = true

[dependencies.tower-make]
version = "0.3"
optional = true

[dependencies.pin-project]
version = "0.4"
optional = true

[build-dependencies.tonic-build]
version = "0.1"
default-features = false
features = [ "transport" ]

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
quickcheck_async = "0.1"
async_ctx = "0.1"
