[package]
name = "blip"
version = "0.1.0-alpha.6"
authors = ["nytopop <ericizoita@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A Rust framework for writing fast and highly resilient in-process gRPC service meshes."
homepage = "https://github.com/nytopop/blip"
repository = "https://github.com/nytopop/blip"
documentation = "https://docs.rs/blip"
keywords = ["rapid", "membership", "mesh", "grpc", "cluster"]
categories = ["network-programming", "asynchronous"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
simulation = [
	"hyper",
	"tower",
	"tower-service",
	"tower-load",
	"tower-make",
	"pin-project"
]

[build-dependencies]
tonic-build = "0.2.0"

[dependencies]
prost = "0.6.1"
bytes = "0.5.4"
http = "0.2.1"
tracing = "0.1.13"
fnv = "1.0.6"
rand = "0.7.3"
failure = "0.1.8"
failure_derive = "0.1.8"

[dependencies.tonic]
version = "0.2.0"
features = [ "transport" , "tls" ]

[dependencies.futures]
version = "0.3.4"
features = [ "alloc" ]

[dependencies.tokio]
version = "0.2.20"
features = [
  "sync",
  "rt-threaded",
  "time",
  "stream",
  "macros"
]

[dependencies.hyper]
version = "0.13.5"
optional = true

[dependencies.tower]
version = "0.3.1"
optional = true

[dependencies.tower-service]
version = "0.3.0"
optional = true

[dependencies.tower-load]
version = "0.3.0"
optional = true

[dependencies.tower-make]
version = "0.3.0"
optional = true

[dependencies.pin-project]
version = "0.4.10"
optional = true

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
quickcheck_async = "0.1"
async_ctx = "0.1"
version-sync = "0.9.0"
